# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b52a5a01ca0c58d8ce4341b926979c297df48462fbe73727f06fbabcb49c566eb240054a757627617543908068f16c29f018af3d98a2653b9fa8ed2c5c748cea

test:
  secret_key_base: 8a67367e88754d9bb51acf6bf14ce13b12c83becb8c3f07370d2250bc1608be1f6f41bc6a67349e584be68ecf23a8861db1b9dbf8f5d391ce011eca842e7b1ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
